# Inventory management system with files
An inventory management system is  used to keep track on their stock of supplies, raw materials, and finished goods. This can assist companies in tracking inventory levels, keeping track of product movement, and automating the purchasing and replenishment procedures.
CREATING DATASET

In [50]:
available_products = {1001: {"name": "avocado", "price": 230,
                             "category": "grocery",
                             "quantity": 10, "date": "10/03/2021"},
                      1002: {"name": "lotion", "price": 250,
                             "category": "beauty & personal",
                             "quantity": 100,
                             "date": "15/07/2021"},
                      1003: {"name": "pain reliever", "price": 500,
                             "category": "health",
                             "quantity": 200, "date": "12/04/2021"},
                      1004: {"name": "dry pasta", "price": 20,
                             "category": "grocery",
                             "quantity": 50, "date": "27/06/2021"},
                      1005: {"name": "toothbrush", "price": 700,
                             "category": "beauty & personal",
                             "quantity": 100,
                             "date": "30/01/2021"},
                      1006: {"name": "halloween candy", "price": 33,
                             "category": "grocery",
                             "quantity": 56, "date": "22/02/2021"},
                      1007: {"name": "mascara", "price": 765,
                             "category": "beauty & personal",
                             "quantity": 70,
                             "date": "11/03/2021"},
                      1008: {"name": "capsicum", "price": 764,
                             "category": "grocery",
                             "quantity": 90, "date": "16/02/2021"},
                      1009: {"name": "blush", "price": 87,
                             "category": "beauty & personal",
                             "quantity": 50, "date": "17/07/2021"},
                      1010: {"name": "granola bars", "price": 24,
                             "category": "grocery", "quantity": 60,
                             "date": "20/05/2021"},
                      }

In [42]:
inventory=available_products

In [43]:
def add_product(id,name,price,category,quantity,data):
  inventory[id]=[name,price,category,quantity,data]
def remove_product(id):
  del inventory[id]
def update(id,name=None,price=None,quantity=None):
  if name:
    inventory[id]=name
  if price:
    inventory[id]=price
  if quantity:
    inventory[id]=category  
  if quantity:
    inventory[id]=quantity 
  if quantity:
    inventory[id]=data          


In [44]:
def save_inventory(filename):
  with open(filename,'w') as f:
    inven_json=json.dump(inventory,f)
  return inven_json  
def load_inventory(filename):
  with open(filename,'r') as f:
    inventory=json.load(f)    

In [45]:
add_product('1011','vodka',300,'drinks',70,'23/10/2021')
save_inventory('inventory.json')


In [46]:
load_inventory('inventory.json')
for product_id,data in inventory.items():
  print(product_id, data)

1001 {'name': 'avocado', 'price': 230, 'category': 'grocery', 'quantity': 10, 'date': '10/03/2021'}
1002 {'name': 'lotion', 'price': 250, 'category': 'beauty & personal', 'quantity': 100, 'date': '15/07/2021'}
1003 {'name': 'pain reliever', 'price': 500, 'category': 'health', 'quantity': 200, 'date': '12/04/2021'}
1004 {'name': 'dry pasta', 'price': 20, 'category': 'grocery', 'quantity': 50, 'date': '27/06/2021'}
1005 {'name': 'toothbrush', 'price': 700, 'category': 'beauty & personal', 'quantity': 100, 'date': '30/01/2021'}
1006 {'name': 'halloween candy', 'price': 33, 'category': 'grocery', 'quantity': 56, 'date': '22/02/2021'}
1007 {'name': 'mascara', 'price': 765, 'category': 'beauty & personal', 'quantity': 70, 'date': '11/03/2021'}
1008 {'name': 'capsicum', 'price': 764, 'category': 'grocery', 'quantity': 90, 'date': '16/02/2021'}
1009 {'name': 'blush', 'price': 87, 'category': 'beauty & personal', 'quantity': 50, 'date': '17/07/2021'}
1010 {'name': 'granola bars', 'price': 24, '

# Inventory management system with json
Inventory management system with Json is managing files,track inventory ,handle , GST billing with javascript object notation.It is lightweight data interchange format that is easy to read and write and  widely used in web applications.

In [51]:
import json

In [52]:
js=json.dumps(available_products)

In [53]:
fd=open('data.json','w')
fd.write(js)

1100

In [55]:
fd=open('data.json','r')
txt=fd.read()
data=json.loads(txt)
fd.close()

In [56]:
print(data.items())

dict_items([('1001', {'name': 'avocado', 'price': 230, 'category': 'grocery', 'quantity': 10, 'date': '10/03/2021'}), ('1002', {'name': 'lotion', 'price': 250, 'category': 'beauty & personal', 'quantity': 100, 'date': '15/07/2021'}), ('1003', {'name': 'pain reliever', 'price': 500, 'category': 'health', 'quantity': 200, 'date': '12/04/2021'}), ('1004', {'name': 'dry pasta', 'price': 20, 'category': 'grocery', 'quantity': 50, 'date': '27/06/2021'}), ('1005', {'name': 'toothbrush', 'price': 700, 'category': 'beauty & personal', 'quantity': 100, 'date': '30/01/2021'}), ('1006', {'name': 'halloween candy', 'price': 33, 'category': 'grocery', 'quantity': 56, 'date': '22/02/2021'}), ('1007', {'name': 'mascara', 'price': 765, 'category': 'beauty & personal', 'quantity': 70, 'date': '11/03/2021'}), ('1008', {'name': 'capsicum', 'price': 764, 'category': 'grocery', 'quantity': 90, 'date': '16/02/2021'}), ('1009', {'name': 'blush', 'price': 87, 'category': 'beauty & personal', 'quantity': 50, 'd

In [57]:
print(data.keys())

dict_keys(['1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '1010'])


Making datafarme

In [58]:
for i  in data.keys():
  for j in data[i].keys():
    df[j]=data[i][j]

In [59]:
df

ID          name  price category  quantity        date
0  1001  granola bars     24  grocery        60  20/05/2021
1  1002  granola bars     24  grocery        60  20/05/2021
2  1003  granola bars     24  grocery        60  20/05/2021
3  1004  granola bars     24  grocery        60  20/05/2021
4  1005  granola bars     24  grocery        60  20/05/2021
5  1006  granola bars     24  grocery        60  20/05/2021
6  1007  granola bars     24  grocery        60  20/05/2021
7  1008  granola bars     24  grocery        60  20/05/2021
8  1009  granola bars     24  grocery        60  20/05/2021
9  1010  granola bars     24  grocery        60  20/05/2021

uploading data in google drive

In [60]:
from google.colab import drive

drive.mount('/content/drive')
path = '/content/drive/My Drive/task.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df.to_csv(f)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Reading data from google drive

In [61]:
path= '/content/drive/My Drive/task.csv'
new_Df=pd.read_csv(path)

In [62]:
new_Df

Unnamed: 0    ID          name  price category  quantity        date
0           0  1001  granola bars     24  grocery        60  20/05/2021
1           1  1002  granola bars     24  grocery        60  20/05/2021
2           2  1003  granola bars     24  grocery        60  20/05/2021
3           3  1004  granola bars     24  grocery        60  20/05/2021
4           4  1005  granola bars     24  grocery        60  20/05/2021
5           5  1006  granola bars     24  grocery        60  20/05/2021
6           6  1007  granola bars     24  grocery        60  20/05/2021
7           7  1008  granola bars     24  grocery        60  20/05/2021
8           8  1009  granola bars     24  grocery        60  20/05/2021
9           9  1010  granola bars     24  grocery        60  20/05/2021

# NUMPY

---

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the numpy package:

In [63]:
import numpy as np

# Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [64]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [65]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [66]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [67]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [68]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [69]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [70]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)
d[0].dtype

[[1. 0.]
 [0. 1.]]


dtype('float64')

In [71]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.44904902 0.0482739 ]
 [0.5959972  0.17666968]]


# Array Indexing
Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [72]:
import numpy as np

# Create a rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [73]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [75]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [76]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [77]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [78]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


# DATATYPES
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [79]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


## ARRAY MATHE
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [80]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [81]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [82]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [83]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [84]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [85]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the @ operator which is equivalent to numpy's dot operator

In [86]:
print(v @ w)

219


In [87]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [88]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [89]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [90]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [91]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


# Broadcasting
roadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [92]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [93]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [94]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [95]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [96]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [97]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [98]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w))

[[ 5  9]
 [ 6 10]
 [ 7 11]]


In [99]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [100]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]
