In [95]:
import torch
import torch.nn as nn
from torch.utils.data  import TensorDataset
from torch.utils.data import DataLoader
import torch.nn.functional as f
import numpy as np

In [96]:
inputs=np.array([[73,67,43],
                [91,88,64],
                [87,134,58],
                [102,43,37],
                [69,96,70]],dtype='float32')
targets=np.array([[56,70],
                 [81,101],
                 [119,133],
                 [22,37],
                 [103,119]],dtype='float32')

In [97]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [98]:
train_ds=TensorDataset(inputs,targets)

In [99]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [100]:
batch_size=2

In [101]:
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [102]:
for xb,yb in train_dl:
    print('btach:')
    print(xb)
    print(yb)

btach:
tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.]])
tensor([[103., 119.],
        [119., 133.]])
btach:
tensor([[102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[22., 37.],
        [56., 70.]])
btach:
tensor([[91., 88., 64.]])
tensor([[ 81., 101.]])


In [103]:
model=nn.Linear(3,2)
preds=model(inputs)
print(preds)

tensor([[-55.7548, -40.6705],
        [-69.3951, -54.7837],
        [-89.9842, -43.2874],
        [-59.8536, -54.3494],
        [-61.2682, -46.6214]], grad_fn=<AddmmBackward0>)


In [104]:
loss_fn=f.mse_loss
loss=loss_fn(model(inputs),targets)
loss

tensor(21583.5176, grad_fn=<MseLossBackward0>)

In [105]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [106]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred=model(xb)
            loss=loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            if(epoch+1)%10 ==0:
                print('Epoch[{}/{}],loss:{:4f}'.format(epoch+1,num_epochs,loss))


In [107]:
fit(100,model,loss_fn,opt,train_dl)

Epoch[10/100],loss:187.296265
Epoch[10/100],loss:453.331390
Epoch[10/100],loss:34.870544
Epoch[20/100],loss:264.910461
Epoch[20/100],loss:119.079445
Epoch[20/100],loss:193.336075
Epoch[30/100],loss:27.931942
Epoch[30/100],loss:249.664017
Epoch[30/100],loss:159.453857
Epoch[40/100],loss:132.893097
Epoch[40/100],loss:126.371460
Epoch[40/100],loss:25.720387
Epoch[50/100],loss:76.443466
Epoch[50/100],loss:128.980667
Epoch[50/100],loss:11.025831
Epoch[60/100],loss:70.668915
Epoch[60/100],loss:60.710587
Epoch[60/100],loss:67.311867
Epoch[70/100],loss:12.393796
Epoch[70/100],loss:62.743706
Epoch[70/100],loss:118.280930
Epoch[80/100],loss:35.477139
Epoch[80/100],loss:36.158897
Epoch[80/100],loss:75.939087
Epoch[90/100],loss:24.004986
Epoch[90/100],loss:53.745464
Epoch[90/100],loss:41.028397
Epoch[100/100],loss:20.168528
Epoch[100/100],loss:32.632416
Epoch[100/100],loss:61.298729


In [108]:

preds=model(inputs)

In [109]:
preds

tensor([[ 58.4963,  73.1231],
        [ 83.6814,  98.3612],
        [115.5043, 144.1276],
        [ 26.5950,  44.2813],
        [101.1932, 110.2015]], grad_fn=<AddmmBackward0>)

In [111]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [110]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3243,  0.7575,  0.7197],
         [-0.0953,  1.0209,  0.2626]], requires_grad=True),
 Parameter containing:
 tensor([0.4667, 0.3895], requires_grad=True)]